### ISSUE TITLE
Issue with rtri and MLE: Unreliable ρ Estimates in MLE When Using von Mises as one of the Marginals

### ISSUE THREAD

**Issue by chriscmr** [Sophia-Loizidou/Trivariate-wrapped-Cauchy-copula#1]
I encountered issues when using the `rtri `function for random variate generation with von Mises as one of the marginals.

```
x <- rtri(1500, rho12 = 1, rho13 = 0.25, rho23 = 4, 
          marginals = c('vonmises', 'weibull', 'weibull'), 
          params1 = list(mu = 2, kappa = 0.2),params2 = list(shape = 1, scale = 1), params3 = list(shape = 1, scale = 1))

# Estimating the maximum likelihood estimates of the parameters
parameters <- mle.copula(x, ninipar = 100, max = 50, min = -50,
                         marginals = c('vonmises', 'weibull', 'weibull'))
# Copula parameters
parameters[c('rho12', 'rho13', 'rho23')]
parameters$params1
parameters$params2
parameters$params3
```

While running the `rtri` function, the following warning appears:
```
Warning message in as.circular(x):
"an object is coerced to the class 'circular' using default value for the following components:
  type: 'angles'
  units: 'radians'
  template: 'none'
  modulo: 'asis'
  zero: 0
  rotation: 'counter'
conversion.circularx[[i]]value$typevalue$unitsvalue$templatevalue$modulovalue$zerovalue$rotation"
Warning message in as.circular(x):
"an object is coerced to the class 'circular' using default value for the following components:
  type: 'angles'
  units: 'radians'
  template: 'none'
  modulo: 'asis'
  zero: 0
  rotation: 'counter'
conversion.circularx[[i]]value$typevalue$unitsvalue$templatevalue$modulovalue$zerovalue$rotation"
```
When estimating maximum likelihood parameters using mle.copula, the estimation for two rho are wrong:
```
$rho12
0.181022355614615
$rho13
0.722999146547377
$rho23
7.64064467311849
```
If I try with this marginals `c('vonmises', 'vonmises', 'wrapped Cauchy')`, the estimates become even negative
```
$rho12
1.08183689466289
$rho13
-0.25532462533069
$rho23
-3.62030790258439
```

Thanks in advance.

**Comment by Sophia-Loizidou** [comment]
Dear Chris,

The warning appears by default by the use of some functions of the package circular. The warnings are now being suppressed so you should not be getting them anymore with the new version of the code.

When you fit the distribution with von Mises and weibull marginal distributions, the function has to calculate 8 parameters (2 for the copula and 2 for each of the marginal distributions). Due to this, more data are required to recover the parameters you initially set when generating the data. If you increase the sample size, you will notice that the parameters are closer to the ones you chose. It is also worthwhile to note that the confidence interval of the parameters with higher value is larger than parameters with lower values. So, it is expected that in this case the estimate of the parameter rho13 will be closer to the true one rather than the estimate of rho23.

About your last question, since you are fitting a different distribution on the data, it is not expected that the mle will recover the values you had set initially. Please also note that weibull distribution is used for linear data while all others supported by this code are to be used with circular data.
